# Generated by Django 5.2 on 2026-05-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('coverage', models.CharField(blank=True, max_length=20)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('days', models.PositiveIntegerField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deps', models.ManyToManyField(blank=True, related_name='successors', to='tasks.task')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
    ]
